apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstapi
  template:
    metadata:
      labels:
        app: firstapi
    spec:
      containers:
      - name: firstapi-container
        image: farahbhr/firstminimalapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: log
            mountPath: /app/logs  #logs path inside the container
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: pv-claim
