
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume"
spec:
  storageClassName: my-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: /data/pv
    type: DirectoryOrCreate
#  env:
    # Obtain the PodName to create the corresponding data directory for the pod on the host. 
#  - name: POD_NAME
#    valueFrom:
#      fieldRef:
#        fieldPath: metadata.name
#  - name: POD_DATA_DIR
#    value: /data/$(POD_NAME)
