
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume"
spec:
  storageClassName: my-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: /data/pv
    type: DirectoryOrCreate

