#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: myapp-log-pvc
#spec:
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: local-storage
#  resources:
#    requests:
#      storage: 1Gi
#  volumeName: myapp-log
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pv-claim"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
