apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secondapi
  template:
    metadata:
      labels:
        app: secondapi
    spec:
      containers:
      - name: secondapi-container
        image: farahbhr/secondminimalapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: log2
            mountPath: /app/logs  #logs path inside the container
            subPath: second
#        env:
        # Obtain the PodName to create the corresponding data directory for the pod on the host.
#        - name: POD_NAME
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.name
#        - name: POD_DATA_DIR
#          value: /data/$(POD_NAME)
      volumes:
      - name: log2
        persistentVolumeClaim:
          claimName: pv-c
---
apiVersion: v1
kind: Service
metadata:
  name: secondapi-service
spec:
  selector:
    app: secondapi
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008

